### ISSUE TITLE
Zoom is not optimized

### ISSUE THREAD

**Issue by NathanBnm** [lainsce/aesop#22]
I think you should offer more zoom options, currently the PDF view is way to little, I can't read any document without zooming, but zoom doesn't fit the window, the PDF is like blocked in a defined rectangle.

Here are some screenshots:

![image](https://user-images.githubusercontent.com/45366162/57178177-0f60bf00-6e6d-11e9-8c26-97ff13379a82.png)

![image](https://user-images.githubusercontent.com/45366162/57178188-21426200-6e6d-11e9-8774-bb1d3283295d.png)

**Comment by lainsce** [comment]
I'm trying to do this for months actually. It's been difficult.

**Comment by lainsce** [comment]
Fixed :tada:

**Comment by NathanBnm** [comment]
@lainsce there is still an issue with the zoom level. When you zoom at a certain point. It's possible to drag the view horizontaly, but verticaly it's broken. As you can see on this screenshot. I cannot scroll more verticaly:

![image](https://user-images.githubusercontent.com/45366162/62409822-5467cf00-b5dd-11e9-89c6-c6e581d638c3.png)

**Comment by lainsce** [comment]
In the screenshot it seems the page got already to the bottom, not having more content as intended.

**Comment by NathanBnm** [comment]
Whoops It's not the good one x)

**Comment by NathanBnm** [comment]
I forgot to add the second screenshot. Here it is:

![image](https://user-images.githubusercontent.com/45366162/62411696-86862a80-b5f7-11e9-8265-036f8fea0e83.png)

**Comment by NathanBnm** [comment]
And here at maximum zoom level, I cannot read the half of the page:

![image](https://user-images.githubusercontent.com/45366162/62411713-addcf780-b5f7-11e9-9e31-a6296f92a171.png)
